# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geek',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='geek_afap_logs',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('log_status', models.IntegerField()),
                ('log_time', models.TextField(max_length=255, null=True)),
                ('log_details', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_forums',
            fields=[
                ('forum_id', models.IntegerField(primary_key=True, serialize=False)),
                ('forum_name', models.TextField(max_length=150)),
                ('forum_slug', models.TextField(max_length=255)),
                ('forum_desc', models.TextField()),
                ('forum_parent', models.IntegerField(default=0)),
                ('forum_order', models.IntegerField(default=0)),
                ('topics', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_meta',
            fields=[
                ('meta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_type', models.TextField(max_length=16)),
                ('object_id', models.IntegerField(default=0)),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('forum_id', models.IntegerField(default=1)),
                ('topic_id', models.IntegerField(default=1)),
                ('poster_id', models.IntegerField(default=0)),
                ('post_text', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('poster_ip', models.TextField()),
                ('post_status', models.IntegerField(default=0)),
                ('post_position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_term_relationships',
            fields=[
                ('object_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('term_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_term_taxonomy',
            fields=[
                ('term_taxonomy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_id', models.IntegerField(default=0)),
                ('taxonomy', models.IntegerField()),
                ('description', models.TextField()),
                ('parent', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bb_topics',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_title', models.IntegerField()),
                ('topic_slug', models.IntegerField()),
                ('topic_poster', models.IntegerField(default=0)),
                ('topic_poster_name', models.IntegerField()),
                ('topic_last_poster', models.IntegerField(default=0)),
                ('topic_last_poster_name', models.IntegerField()),
                ('topic_start_time', models.DateTimeField(auto_now=True)),
                ('topic_time', models.DateTimeField(auto_now=True)),
                ('forum_id', models.IntegerField(default=1)),
                ('topic_status', models.IntegerField(default=0)),
                ('topic_open', models.IntegerField(default=1)),
                ('topic_last_post_id', models.IntegerField(default=1)),
                ('topic_sticky', models.IntegerField(default=0)),
                ('topic_posts', models.IntegerField(default=0)),
                ('tag_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('component', models.IntegerField()),
                ('type', models.IntegerField()),
                ('action', models.TextField()),
                ('content', models.TextField()),
                ('primary_link', models.TextField()),
                ('item_id', models.IntegerField()),
                ('secondary_item_id', models.IntegerField(default=None, null=True)),
                ('date_recorded', models.DateField()),
                ('hide_sitewide', models.IntegerField(default=0)),
                ('mptt_left', models.IntegerField(default=0)),
                ('mptt_right', models.IntegerField(default=0)),
                ('is_spam', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_activity_meta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_id', models.IntegerField()),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_friends',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('initiator_user_id', models.IntegerField()),
                ('friend_user_id', models.IntegerField()),
                ('is_confirmed', models.IntegerField()),
                ('is_limited', models.IntegerField()),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField()),
                ('name', models.IntegerField()),
                ('slug', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('enable_forum', models.IntegerField(default=1)),
                ('date_created', models.DateField()),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_groups_groupmeta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('meta_key', models.IntegerField()),
                ('meta_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_groups_members',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('inviter_id', models.IntegerField()),
                ('is_admin', models.IntegerField(default=0)),
                ('is_mod', models.IntegerField(default=0)),
                ('user_title', models.IntegerField()),
                ('date_modified', models.DateTimeField()),
                ('comments', models.TimeField()),
                ('is_confirmed', models.IntegerField(default=0)),
                ('is_banned', models.IntegerField(default=0)),
                ('invite_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_messages_messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('thread_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('subject', models.IntegerField()),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_messages_meta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField()),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_messages_notices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.IntegerField()),
                ('message', models.TextField()),
                ('date_sent', models.DateField()),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_messages_recipients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('thread_id', models.IntegerField()),
                ('unread_count', models.IntegerField(default=0)),
                ('sender_only', models.IntegerField(default=0)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_notifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('secondary_item_id', models.IntegerField(default=None, null=True)),
                ('component_name', models.IntegerField()),
                ('component_action', models.IntegerField()),
                ('date_notified', models.DateTimeField()),
                ('is_new', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_notifications_meta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_id', models.IntegerField()),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_user_blogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('blog_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_user_blogs_blogmeta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_id', models.IntegerField()),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_xprofile_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('value', models.TextField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_xprofile_fields',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('name', models.IntegerField()),
                ('description', models.TextField()),
                ('is_required', models.IntegerField(default=0)),
                ('is_default_option', models.IntegerField(default=0)),
                ('field_order', models.IntegerField(default=0)),
                ('option_order', models.IntegerField(default=0)),
                ('order_by', models.IntegerField()),
                ('can_delete', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_xprofile_groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('description', models.TextField()),
                ('group_order', models.IntegerField(default=0)),
                ('can_delete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_bp_xprofile_meta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('object_type', models.IntegerField()),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_commentmeta',
            fields=[
                ('meta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField(default=0)),
                ('meta_key', models.IntegerField(default=None, null=True)),
                ('meta_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geek_comments',
            fields=[
                ('comment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_post_ID', models.IntegerField(default=0)),
                ('comment_author', models.TextField()),
                ('comment_author_email', models.IntegerField()),
                ('comment_author_url', models.IntegerField()),
                ('comment_author_IP', models.IntegerField()),
                ('comment_date', models.DateTimeField(default=0)),
                ('comment_date_gmt', models.DateTimeField(default=0)),
                ('comment_content', models.TextField()),
                ('comment_karma', models.IntegerField(default=0)),
                ('comment_approved', models.IntegerField(default=1)),
                ('comment_agent', models.IntegerField()),
                ('comment_type', models.IntegerField()),
                ('comment_parent', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='geek_links',
            fields=[
                ('link_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_url', models.IntegerField()),
                ('link_name', models.IntegerField()),
                ('link_image', models.IntegerField()),
                ('link_target', models.IntegerField()),
                ('link_description', models.IntegerField()),
                ('link_visible', models.IntegerField()),
                ('link_owner', models.IntegerField()),
                ('link_rating', models.IntegerField()),
                ('link_updated', models.DateTimeField(default=0)),
                ('link_rel', models.IntegerField()),
                ('link_notes', models.TextField()),
                ('link_rss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='geek_login_log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.IntegerField()),
                ('msg', models.IntegerField()),
                ('l_added', models.DateField()),
                ('l_status', models.IntegerField()),
            ],
        ),
    ]
