# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20170317_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('OS', 'OS'), ('LANGUAGE', 'LANGUAGE'), ('CMS', 'CMS'), ('SEO', 'SEO'), ('GAME', 'GAME'), ('HOW_TO', 'HOW TO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('post_pic', models.ImageField(null=True, upload_to=b'')),
                ('no_like', models.IntegerField(default=0)),
                ('no_comments', models.IntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media/image')),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='geek',
        ),
        migrations.DeleteModel(
            name='geek_afap_logs',
        ),
        migrations.DeleteModel(
            name='geek_bb_forums',
        ),
        migrations.DeleteModel(
            name='geek_bb_meta',
        ),
        migrations.DeleteModel(
            name='geek_bb_posts',
        ),
        migrations.DeleteModel(
            name='geek_bb_term_relationships',
        ),
        migrations.DeleteModel(
            name='geek_bb_term_taxonomy',
        ),
        migrations.DeleteModel(
            name='geek_bb_topics',
        ),
        migrations.DeleteModel(
            name='geek_bp_activity',
        ),
        migrations.DeleteModel(
            name='geek_bp_activity_meta',
        ),
        migrations.DeleteModel(
            name='geek_bp_friends',
        ),
        migrations.DeleteModel(
            name='geek_bp_groups',
        ),
        migrations.DeleteModel(
            name='geek_bp_groups_groupmeta',
        ),
        migrations.DeleteModel(
            name='geek_bp_groups_members',
        ),
        migrations.DeleteModel(
            name='geek_bp_messages_messages',
        ),
        migrations.DeleteModel(
            name='geek_bp_messages_meta',
        ),
        migrations.DeleteModel(
            name='geek_bp_messages_notices',
        ),
        migrations.DeleteModel(
            name='geek_bp_messages_recipients',
        ),
        migrations.DeleteModel(
            name='geek_bp_notifications',
        ),
        migrations.DeleteModel(
            name='geek_bp_notifications_meta',
        ),
        migrations.DeleteModel(
            name='geek_bp_user_blogs',
        ),
        migrations.DeleteModel(
            name='geek_bp_user_blogs_blogmeta',
        ),
        migrations.DeleteModel(
            name='geek_bp_xprofile_data',
        ),
        migrations.DeleteModel(
            name='geek_bp_xprofile_fields',
        ),
        migrations.DeleteModel(
            name='geek_bp_xprofile_groups',
        ),
        migrations.DeleteModel(
            name='geek_bp_xprofile_meta',
        ),
        migrations.DeleteModel(
            name='geek_commentmeta',
        ),
        migrations.DeleteModel(
            name='geek_comments',
        ),
        migrations.DeleteModel(
            name='geek_links',
        ),
        migrations.DeleteModel(
            name='geek_login_log',
        ),
        migrations.AddField(
            model_name='postdetails',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.UserDetails'),
        ),
    ]
